"""
Visualization 8: Frequency Distribution Kernel Matrix Heatmap Comparison

Compares kernel matrices generated by different frequency distributions:
- TCFMamba (a=3): Smooth, wide-band similarity
- Transformer (a=-1): Sharp, local similarity
- Linear (a=1): Periodic banding

Mathematical Background:
-------------------------
Kernel matrix: K_{ij} = Re(K(q_i - q_j)) = Σ cos(ω_k · (q_i - q_j))

Different frequency distributions produce different similarity patterns:
1. TCFMamba (power a=3): Concentrated low frequencies → smooth decay
2. Transformer (geometric): Spread frequencies → rapid local decay
3. Linear: Uniform spacing → periodic interference patterns

POI Recommendation Implication:
- TCFMamba captures "nearby" POIs in a broader sense (200-500m)
- Transformer focuses on immediate neighbors only
- This matches real POI visit patterns better

Reference: math.md Section 4 (Kernel matrix properties, comparison)
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent))
from base import KernelFunction, FrequencyFunction, setup_plot_style, save_figure
from base.plot_utils import POWER_COLORS, COLORS
from base.viz_logger import VizLogger


def visualize_frequency_kernel_heatmap(output_dir: Path = None):
    """
    Generate kernel matrix comparison for different frequency distributions.
    """
    if output_dir is None:
        output_dir = Path(__file__).parent.parent / "output"
    
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Initialize logger
    logger = VizLogger('8_frequency_kernel_heatmap')
    logger.set_description('Frequency-Kernel Heatmap Comparison')
    logger.add_finding('TCFMamba (a=3) produces smooth, wide-band similarity', 'empirical')
    logger.add_finding('Transformer (a=-1) creates sharp, local similarity', 'comparison')
    logger.log_parameter('kernel_formula', 'K_ij = Σ cos(ω_k · (q_i - q_j))')
    logger.log_parameter('dim', 64)
    logger.log_parameter('n_points', 60)
    
    setup_plot_style(figsize=(15, 12))
    
    # Parameters
    dim = 64
    n_points = 60
    positions = np.linspace(0, 1000, n_points)  # 0-1000 meters
    
    # Three distributions to compare
    configs = [
        (-1.0, 'Transformer', 'Geometric distribution\n(a=-1)'),
        (1.0, 'Linear', 'Uniform spacing\n(a=1)'),
        (3.0, 'TCFMamba', 'Power-law concentrated\n(a=3)')
    ]
    
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    
    for idx, (power, name, desc) in enumerate(configs):
        # Compute kernel matrix
        freq_func = FrequencyFunction(dim, power)
        kernel = KernelFunction(freq_func)
        K_matrix = kernel.compute_matrix(positions)
        
        # Plot 1: Kernel matrix heatmap (top row)
        ax_heatmap = axes[0, idx]
        vmax = 32  # Fixed scale for comparison
        im = ax_heatmap.imshow(K_matrix, cmap='RdBu_r', aspect='auto',
                              vmin=-vmax, vmax=vmax)
        ax_heatmap.set_title(f'{name}\n{desc}', fontsize=11)
        ax_heatmap.set_xlabel('Position j', fontsize=9)
        ax_heatmap.set_ylabel('Position i', fontsize=9)
        
        # Add colorbar
        cbar = plt.colorbar(im, ax=ax_heatmap, fraction=0.046, pad=0.04)
        cbar.set_label('K_{ij}', fontsize=8)
        
        # Plot 2: Cross-section (middle row, moved to bottom)
        ax_cross = axes[1, idx]
        
        # Take diagonal cross-section (distance from center)
        center = n_points // 2
        cross_section = K_matrix[center, :]
        distances = np.abs(positions - positions[center])
        
        ax_cross.plot(distances, cross_section, linewidth=2.5, 
                     color=POWER_COLORS.get(power, COLORS['dark']))
        ax_cross.axhline(y=0, color='gray', linewidth=0.5, linestyle='--')
        ax_cross.axvline(x=0, color='gray', linewidth=0.5, linestyle='--')
        ax_cross.set_xlabel('Distance from Center (meters)', fontsize=9)
        ax_cross.set_ylabel('Kernel Value', fontsize=9)
        ax_cross.set_title('Cross-Section (Central Row)', fontsize=11)
        ax_cross.grid(True, alpha=0.3)
        ax_cross.set_xlim([0, 500])  # Focus on 0-500m range
        
        # Add annotations
        max_val = np.max(cross_section)
        min_val = np.min(cross_section)
        ax_cross.text(0.95, 0.95, f'Max: {max_val:.1f}\nMin: {min_val:.1f}',
                     transform=ax_cross.transAxes, fontsize=8,
                     verticalalignment='top', horizontalalignment='right',
                     bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))
    
    plt.suptitle('Frequency Distribution Kernel Matrix Comparison\n' +
                 'K_{ij} = Σ cos(ω_k · (q_i - q_j)): How frequency distribution shapes similarity patterns',
                 fontsize=14, fontweight='bold', y=0.98)
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    
    save_figure(fig, '8_frequency_kernel_heatmap', output_dir)
    logger.log_figure(output_dir / '8_frequency_kernel_heatmap.png',
                     title='Frequency-Kernel Heatmap Comparison',
                     fig_type='multi_heatmap')
    plt.close(fig)
    
    # Log kernel matrix data
    dim = 64
    n_points = 60
    positions = np.linspace(0, 1000, n_points)
    powers = [-1.0, 1.0, 3.0]
    labels = ['Transformer', 'Linear', 'TCFMamba']
    
    for power, label in zip(powers, labels):
        freq_func = FrequencyFunction(dim, power)
        kernel = KernelFunction(freq_func)
        K_matrix = kernel.compute_matrix(positions)
        
        # Log matrix
        logger.log_matrix(f'kernel_matrix_a{power}', K_matrix,
                         metadata={'power': power, 'label': label, 'n_points': n_points})
        
        # Log cross-section
        center_idx = n_points // 2
        cross_section = K_matrix[center_idx, :]
        distances = np.abs(positions - positions[center_idx])
        logger.log_series(f'kernel_cross_section_a{power}', distances, cross_section,
                         x_label='Distance Δq (meters)', y_label='K(Δq)',
                         metadata={'power': power, 'label': label, 'center': positions[center_idx]})
        
        # Log statistics
        logger.log_metric(f'matrix_max_a{power}', float(np.max(K_matrix)),
                         context={'power': power, 'label': label})
        logger.log_metric(f'matrix_min_a{power}', float(np.min(K_matrix)),
                         context={'power': power, 'label': label})
        logger.log_metric(f'diagonal_mean_a{power}', float(np.mean(np.diag(K_matrix))),
                         context={'power': power, 'label': label})
    
    # Log comparison
    logger.log_comparison('kernel_similarity_patterns', [
        {'label': 'Transformer (a=-1)', 'value': -1.0, 'properties': {
            'pattern': 'sharp_local', 'range': 'short', 'suitability': 'local_attention'}},
        {'label': 'Linear (a=1)', 'value': 1.0, 'properties': {
            'pattern': 'periodic_banding', 'range': 'medium', 'suitability': 'periodic_tasks'}},
        {'label': 'TCFMamba (a=3)', 'value': 3.0, 'properties': {
            'pattern': 'smooth_wide', 'range': 'long', 'suitability': 'poi_recommendation'}}
    ])
    
    # Create additional detailed comparison figure
    create_detailed_comparison(output_dir, dim, positions)
    logger.log_figure(output_dir / '8_frequency_kernel_crosssections.png',
                     title='Kernel Cross-Section Analysis',
                     fig_type='multi_subplot')
    
    # Save logger data
    logger.save()
    print("Visualization 8 completed: Frequency Kernel Heatmap Comparison")


def create_detailed_comparison(output_dir: Path, dim: int, positions: np.ndarray):
    """Create detailed comparison with multiple cross-sections."""
    
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    
    powers = [-1.0, 1.0, 3.0]
    labels = ['Transformer', 'Linear', 'TCFMamba']
    
    for ax, power, label in zip(axes, powers, labels):
        freq_func = FrequencyFunction(dim, power)
        kernel = KernelFunction(freq_func)
        K_matrix = kernel.compute_matrix(positions)
        
        # Multiple cross-sections at different distances
        centers = [15, 30, 45]  # Different center positions
        colors_section = ['#3498db', '#2ecc71', '#e74c3c']
        
        for center, color_sec in zip(centers, colors_section):
            cross_section = K_matrix[center, :]
            distances = np.abs(positions - positions[center])
            ax.plot(distances, cross_section, linewidth=2, 
                   label=f'Center at {positions[center]:.0f}m', color=color_sec, alpha=0.7)
        
        ax.set_xlabel('Distance (meters)', fontsize=10)
        ax.set_ylabel('Kernel Value K(Δq)', fontsize=10)
        ax.set_title(f'{label} (a={power})', fontsize=12, fontweight='bold')
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)
        ax.axhline(y=0, color='gray', linewidth=0.5)
        ax.set_xlim([0, 500])
    
    plt.suptitle('Cross-Section Analysis: Kernel Behavior at Different Positions',
                fontsize=13, fontweight='bold')
    plt.tight_layout()
    
    save_figure(fig, '8_frequency_kernel_crosssections', output_dir)
    plt.close(fig)


if __name__ == '__main__':
    visualize_frequency_kernel_heatmap()
